# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.231.6/containers/go/.devcontainer/base.Dockerfile

FROM mcr.microsoft.com/vscode/devcontainers/go:0-1.18-bullseye